baseURL: https://blog.rahulgadre.com # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Rahul's Blogs
paginate: 6
theme: charlolamode



menu:
    main:
        - name: About
          url: https://rahulgadre.com/
          weight: 20
        - name: Contact
          url: /contact/
          weight: 30
       # - name: Blog
       #   url: /blog/
       #   weight: 20
       # - name: Projects
       #   url: /projects/
       #   weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Rahul Gadre


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Rahul Gadre
        description: Hello, I am Rahul. This blog site is for blogs related to career, travel, and life 😊
        imageUrl: "https://raw.githubusercontent.com/rahulgadre/blog.rahulgadre.com/main/images/my-rmnp-pic.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
           - name: Rahul's blogs
             url: https://blog.rahulgadre.com/blog/
    mainSections:
      - articles
      
  #  socialIcons:
      #  - name: twitter
      #    url: "https://twitter.com/rggadre"
      #  - name: github
      #    url: "https://github.com/rahulgadre"
      #  - name: linkedin
      #    url: "https://www.linkedin.com/in/rahulgadre/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "https://raw.githubusercontent.com/rahulgadre/misc-blogs/main/images/rg-gold-300.png"
          favicon16x16: "https://raw.githubusercontent.com/rahulgadre/misc-blogs/main/images/rg-gold-300.png"
          favicon32x32: "https://raw.githubusercontent.com/rahulgadre/misc-blogs/main/images/rg-gold-300.png"
          apple_touch_icon: "https://raw.githubusercontent.com/rahulgadre/misc-blogs/main/images/rg-gold-300.png"
          safari_pinned_tab: "https://raw.githubusercontent.com/rahulgadre/misc-blogs/main/images/rg-gold-300.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
